### ISSUE TITLE
Didn't change the icons on OnePlus 3T (OB 7)

### ISSUE THREAD

**Issue by ajishnair** [ZeevoX/PixelLauncherIcons#1]
Used the same pixel launcher mentioned by you along with the apk. Tried installing both as system and as normal app. Also tried clearing data and deleting the files using root launcher. But icons remained the same!

**Comment by ZeevoX** [comment]
Did any of the icons change? As far as I understand Google Translate should be themed on all devices. Can you try and report back?

Thanks!

**Comment by ajishnair** [comment]
Nope no change in any icons!

**Comment by ZeevoX** [comment]
This is happening because the Pixel Launcher from Android O (versionCode 200+) does not take icons from the Pixel Launcher Icons application anymore. If you want forced round icons, see the modified Pixel Launcher, available [here.](https://github.com/amirzaidi/Launcher3)

Issue closed, project abandoned.
